# Site settings
title: Erik Lynd's Posts
email: lynderik@gmail.com
description: "Erik Lynd blogs here."
baseurl: ""
url: "http://eriklynd.github.io"

# Build settings
markdown: kramdown
permalink: pretty
